remote_theme: eecs485staff/primer-spec
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jemoji
kramdown:
  input: GFM
readme_index:
  remove_originals: true
  with_frontmatter: true

title: Daplin
description: >-
  Dignified Attestation Protocol for Linked Identity Networks —
  an open protocol for decentralized digital identity, cryptographic
  public key exchange, and social trust.
url: https://daplin.org
baseurl: ""

exclude:
  - src/

primerSpec:
  sitemap:
    label: ""
