remote_theme: carlosperate/jekyll-theme-rtd@v1.0.0
plugins:
  - jekyll-remote-theme

title: Daplin
description: >-
  Dignified Attestation Protocol for Linked Identity Networks —
  an open protocol for decentralized digital identity, cryptographic
  public key exchange, and social trust.
url: https://daplin.org
baseurl: ""

repo_url: 'https://github.com/cwlls/daplin'
edit_on_github: false
site_author: Daplin Contributors

search_enabled: true
sticky_navigation: true
prev_next_buttons_location: bottom

hljs_languages:
  - json
  - yaml
  - bash
  - python

exclude:
  - src/
